homework task 2
xJustNeko/FE46-Gilevski pull request #4
Opened 2023-02-07 15:42 UTC by xJustNeko

2023-02-08 16:02 UTC, UladTeachMeSkills requested changes

2023-02-08 16:02 UTC, UladTeachMeSkills commented on axit-project/index.html
> +    <link href="./styles/banner.css" rel="stylesheet">
Сделай один файл index.css и собери там все файлы стилей при помощи @input("./")
Импортируй этот единственный файл сборщик в index.html

2023-02-08 16:02 UTC, UladTeachMeSkills commented on axit-project/index.html
> +                    <button class="banner__button">Download</button>
type button

2023-02-08 16:02 UTC, UladTeachMeSkills commented on axit-project/index.html
> +                    <div class="banner__main"><span>Use the sections you need, remove the ones you don't. Create
Скорее это заголовок или параграф

2023-02-10 09:17 UTC, UladTeachMeSkills requested changes

2023-02-10 09:17 UTC, UladTeachMeSkills commented on axit-project/index.html
>      <link href="./styles/reset.css" rel="stylesheet">
Сброс стилей ты так же можешь подключить в index.css

2023-02-10 09:17 UTC, UladTeachMeSkills commented on axit-project/index.html
> +                    <input type="button" class="banner__button" value="DOWNLOAD">
используй button

2023-02-10 09:17 UTC, UladTeachMeSkills commented on axit-project/styles/banner.css
> +    background-image: url(/axit-project/assets/images/banner.png);
./

2023-02-13 11:04 UTC, UladTeachMeSkills requested changes

2023-02-13 11:04 UTC, UladTeachMeSkills commented on axit-project/index.html
>      <link href="./styles/reset.css" rel="stylesheet">
Тоже запихни в index.css

2023-02-13 11:04 UTC, UladTeachMeSkills commented on axit-project/index.html
>      <title>Document</title>
Замени на название проекта

2023-02-13 11:04 UTC, UladTeachMeSkills commented on axit-project/index.html
> +                    <input type="button" class="banner__button" value="DOWNLOAD">
Замени на кнопку с типом кнопка

2023-02-13 11:04 UTC, UladTeachMeSkills commented on axit-project/styles/banner.css
> +    background-image: url(/axit-project/assets/images/banner.png);
./assets/images/banner.png

2023-02-13 11:04 UTC, UladTeachMeSkills commented on axit-project/styles/banner.css
> +    font-family: "Raleway", sans-serif;
Один стандартный шрифт только в body и больше нигда, другой шрифт -подключается локально к нужному классу

2023-02-13 11:04 UTC, UladTeachMeSkills commented on axit-project/styles/banner.css
> +    font-family: "Open Sans", sans-serif;
Один стандартный шрифт только в body и больше нигда, другой шрифт -подключается локально к нужному классу

2023-02-16 10:59 UTC, xJustNeko commented on axit-project/styles/banner.css
> +    background-image: url(/axit-project/assets/images/banner.png);
не работает так

2023-02-16 12:58 UTC, UladTeachMeSkills approved these changes

2023-02-16 13:02 UTC, merged